apiVersion: v1
kind: Pod
metadata:
  name: rhel-ssh-pod
spec:
  containers:
    - name: rhel
      image: registry.access.redhat.com/ubi9/ubi:latest
      command: ["/bin/bash"]
      args:
        - -c
        - |
          dnf install -y openssh-server python3 tmux && \
          ssh-keygen -A && \
          sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
          echo "root:Asdf_123" | chpasswd && \
          /usr/sbin/sshd -D
      ports:
        - containerPort: 22
